INSERT INTO OWNER (IDOWNER, NAME, LASTNAME, IDCARD, EMAIL) VALUES (1, 'Marco', 'Macias','1315204105','marc.macias96@gmail.com');
INSERT INTO OWNER (IDOWNER, NAME, LASTNAME, IDCARD, EMAIL) VALUES (2, 'Darex', 'León','1803660149','darexleon@gmail.com');
INSERT INTO HOUSE (IDHOUSE, NUMBER, BLOCK) VALUES (1, '1', 'A');
INSERT INTO INCOME (IDINCOME, VALUE, DATE, DESCRIPTION, TYPE) VALUES(1, 12.2, 15-12-2019, 'N/A', 'Efectivo');
