INSERT INTO USER (IDUSER, NAME, PASSWORD) VALUES (1,'admin','$2a$10$d3T14yA7cKYtBL9Oll1g1O.qILE8B4KfQkXtDOD6ZIr9BJ.uWsv6iu');
INSERT INTO USER (IDUSER, NAME, PASSWORD) VALUES (2,'marc','$2a$10$d3T14yA7cKYtBL9Oll1g1O.qILE8B4KfQkXtDOD6ZIr9BJ.uWsv6i');
INSERT INTO USER (IDUSER, NAME, PASSWORD) VALUES (3,'darex','$2a$10$d3T14yA7cKYtBL9Oll1g1O.qILE8B4KfQkXtDOD6ZIr9BJ.uWsv6i');

INSERT INTO ROLE (IDROLE, NAME, IDUSER) VALUES (1,'ROLE_USER-ADMIN',1);
INSERT INTO ROLE (IDROLE, NAME, IDUSER) VALUES (2,'ROLE_USER',2);

INSERT INTO CONDOMINIUM (IDCONDOM,COSTALI , NAME, REFERENCE ,SECTOR, STREET1,STREET2, IDUSER) VALUES (1,20.0, 'VALLE DEL REY','URB. 6 DE DICIEMBRE','CONOCOTO','PRINCESA TOA','ISSAC BARRERA',1 );

INSERT INTO OWNER (IDOWNER, NAME, LASTNAME, IDCARD, EMAIL, IDCONDOM, IDUSER) VALUES (1, 'Marco', 'Macias','1315204105','marc.macias96@gmail.com', 1, 2);

INSERT INTO HOUSE (IDHOUSE, BLOCK, NUMBER , IDCONDOM, IDOWNER) VALUES (1,1,1,1,1);